provider:
  name: faas
functions:
  helloworld:
    lang: python3
    handler: ./helloworld
    image: richsanders/helloworld:latest
  sendmail:
    lang: python3
    handler: ./sendmail
    image: richsanders/sendmail:latest
    secrets:
      - openfaas-cloud
  flask-sendmail:
    lang: python3-flask
    handler: ./flask-sendmail
    image: richsanders/flask-sendmail:latest
    secrets:
      - openfaas-cloud
